### ISSUE TITLE
14-n040br

### ISSUE THREAD

**Issue by pauloborini** [1ukidev/14-v060br-hackintosh#1]
Será que funciona no 14-n040br?

**Comment by pauloborini** [comment]
Não estou conseguindo fazer funcionar e to precisando para tentar trabalhar nele.

**Comment by 1ukidev** [comment]
> Será que funciona no 14-n040br?

Acredito que sim, mas talvez seja necessário alguns ajustes.

**Comment by 1ukidev** [comment]
> Não estou conseguindo fazer funcionar e to precisando para tentar trabalhar nele.

Sabe me dizer o que tá dando errado?

**Comment by pauloborini** [comment]
Ele faz o erase normalmente, mas não deixava eu selecionar para instalar depois na parte de instalação. Estou fazendo um pendrive novo aqui e vou colocar a sua EFI pra testar.

**Comment by pauloborini** [comment]
Ele faz o erase normalmente, mas não deixava eu selecionar para instalar depois na parte de instalação. Estou fazendo um pendrive novo aqui e vou colocar a sua EFI pra testar.

**Comment by pauloborini** [comment]
Consegui instalar utilizando esse EFI, baixei a versão 11.7.2, ficou limitado ao Big Sur, ele não aceitou o Monterey.
Obrigado pela ajuda!
Abraço!

**Comment by pauloborini** [comment]
Consegui instalar utilizando esse EFI, baixei a versão 11.7.2, ficou limitado ao Big Sur, ele não aceitou o Monterey.
Obrigado pela ajuda!
Abraço!

**Comment by 1ukidev** [comment]
👍
